import './globals.css'
import React from "react";

import {Nav} from '@/components/Nav/Nav';
import {Header} from '@/components/Header/Header';
import {Footer} from '@/components/Footer/Footer';

export const metadata = {
    title: {
        default: 'Home » Patitas Felices',
        template: '%s » Patitas Felices'
    },
    description: 'Generated by create next app',
}

export default function HomeLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body>
                <Header/>
                <Nav/>
                {children}
                <Footer/>
            </body>
        </html>
    )
}
